//import 'package:flutter/material.dart';
const purpleOwl = 'assets/icons/PurpleOwl.svg';
const welcomeOwl = 'assets/icons/welcome.svg';
const backButton = 'assets/icons/backButton.svg';
const bulleWelcome = 'assets/icons/bulle1.svg';
const button1 = 'assets/icons/button1.svg';
const homeIcon = 'assets/icons/homeIcon.svg';
const settingsIcon = 'assets/icons/settingsIcon.svg';
const branch2 = 'assets/icons/branchSimple.svg';
const button60 = 'assets/icons/button1-150x60.svg';
const button100 = 'assets/icons/button1-250x100.svg';
const branch = 'assets/icons/branch.svg';
const brin = 'assets/icons/brin.svg';
const brin2 = 'assets/icons/brin2.svg';
const bulle2='assets/icons/bulle2.svg';
const Plus='assets/icons/PlusIcon.svg';
const buttonVersGauche = 'assets/icons/buttonVersGauche.svg';
const buttonVersDroite = 'assets/icons/buttonVersDroite.svg';
const buttonCentre = 'assets/icons/buttonCentre.svg';
const buttonUserSettings = 'assets/icons/UserSettings.svg';
const buttonStatistique = 'assets/icons/Statistique.svg';
const buttonGoTo = 'assets/icons/GoIcon.svg';
const buttonLightDark = 'assets/icons/Light-Dark.svg';
const buttonNoSound = 'assets/icons/noSound.svg';
const buttonNoMusic = 'assets/icons/noMusic.svg';
const buttonMusic = 'assets/icons/Music.svg';
const buttonSound = 'assets/icons/Sound.svg';
const pinkOwl = 'assets/icons/PinkOwl.svg';
const orangeOwl = 'assets/icons/OrangeOwl.svg';
const blueOwl = 'assets/icons/BlueOwl.svg';
const Cercle = 'assets/icons/Cercle.svg';
const Cercle2 = 'assets/icons/Cercle2.svg';
const Owlbranch = 'assets/icons/OwlWithBranch.svg';
const buttonNom = 'assets/icons/buttonNom.svg';
const buttonNon = 'assets/icons/buttonnon.svg';
const buttonOui = 'assets/icons/buttonoui.svg';
const buttonMdp = 'assets/icons/Mdp.svg';
const buttonAvatar = 'assets/icons/Avatar.svg';
const buttonMotdepasse = 'assets/icons/MotDePasse.svg';
const buttonSupp = 'assets/icons/Supprimer.svg';
const buttonNomUser = 'assets/icons/NomUser.svg';
const bullevide = 'assets/icons/bullevide.svg';
const ClassementIcon = 'assets/icons/ClassementIcon.svg';
const PinkAvatar = 'assets/icons/PinkAvatar.svg';
const PurpleAvatar = 'assets/icons/PurpleAvatar.svg';
const OrangeAvatar = 'assets/icons/OrangeAvatar.svg';
const BlueAvatar = 'assets/icons/BlueAvatar.svg';




